//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FaceCounter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Source { get; set; }
        public CameraType Type { get; set; } 
       
    }
}
